#!/usr/bin/env python3
"""
LinkedIn Watcher - Production Ready
Monitors LinkedIn using Node.js Playwright (bypasses Python greenlet issue)
"""

import os
import sys
import json
import time
import logging
import argparse
import subprocess
from datetime import datetime
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('linkedin-watcher.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger('LinkedInWatcher')

class LinkedInWatcher:
    def __init__(self, config_path='linkedin-config.json', vault_path=None, auth_file='auth.json'):
        self.config = self.load_config(config_path)
        self.auth_file = auth_file

        # Determine vault path
        if vault_path:
            self.vault_path = Path(vault_path)
        else:
            current = Path.cwd()
            vault_found = False
            for _ in range(5):
                potential_vault = current / 'Vault'
                if potential_vault.exists():
                    self.vault_path = potential_vault
                    vault_found = True
                    break
                current = current.parent

            if not vault_found:
                self.vault_path = Path('../../../Vault')

        self.needs_action_path = self.vault_path / 'Needs_Action'
        self.check_interval = self.config.get('check_interval', 300)
        self.processed_items = set()

        self.needs_action_path.mkdir(parents=True, exist_ok=True)
        logger.info(f"Vault path: {self.vault_path.absolute()}")
        logger.info(f"Output to: {self.needs_action_path.absolute()}")

    def load_config(self, config_path):
        """Load configuration"""
        try:
            with open(config_path, 'r') as f:
                config = json.load(f)
                logger.info(f"Loaded config from {config_path}")
                return config
        except FileNotFoundError:
            logger.warning(f"Config file not found: {config_path}, using defaults")
            return {
                'check_interval': 300,
                'monitor_messages': True,
                'monitor_notifications': True
            }

    def check_auth_file(self):
        """Check if auth.json exists"""
        if not Path(self.auth_file).exists():
            logger.error(f"Authentication file not found: {self.auth_file}")
            logger.error("Run: python3 -m playwright codegen --save-storage=auth.json linkedin.com")
            logger.error("Then log in to LinkedIn and close the browser to save your session")
            return False
        return True

    def check_linkedin(self):
        """Check LinkedIn using Node.js script"""
        try:
            result = subprocess.run(
                ['node', 'linkedin-checker.js'],
                capture_output=True,
                text=True,
                timeout=60
            )

            if result.returncode != 0:
                logger.error(f"LinkedIn checker failed: {result.stderr}")
                return None

            # Parse JSON output between RESULTS_START and RESULTS_END
            output = result.stdout
            if 'RESULTS_START' in output and 'RESULTS_END' in output:
                json_str = output.split('RESULTS_START')[1].split('RESULTS_END')[0].strip()
                return json.loads(json_str)
            else:
                logger.error("Could not parse LinkedIn checker output")
                return None

        except subprocess.TimeoutExpired:
            logger.error("LinkedIn checker timed out")
            return None
        except Exception as e:
            logger.error(f"Error running LinkedIn checker: {e}")
            return None

    def create_action_file(self, item_type, item_data):
        """Create action file for LinkedIn item"""
        timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
        title = item_data.get('title', 'New Item').replace('/', '-')[:50]
        filename = f"LINKEDIN_{item_type}_{title}_{timestamp}.md"
        filepath = self.needs_action_path / filename

        content = f"""# LINKEDIN {item_type.upper()}: {item_data.get('title', 'New Item')}

**Type:** {item_type}
**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Priority:** MEDIUM

## Content

{item_data.get('content', item_data.get('preview', 'No content available'))}

## Details

"""

        if 'sender' in item_data:
            content += f"**From:** {item_data['sender']}\n"

        content += f"""
## Suggested Actions

- [ ] Review {item_type}
- [ ] Take appropriate action
- [ ] Respond if needed

## Metadata

- Processed: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

*Auto-generated by LinkedIn Watcher*
*Silver Tier - AI Employee*
"""

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)

        logger.info(f"Created action file: {filename}")
        return filepath

    def watch(self, once=False):
        """Main watch loop"""
        logger.info("="*60)
        logger.info("LinkedIn Watcher - Silver Tier")
        logger.info("="*60)

        if not self.check_auth_file():
            return

        logger.info(f"Using authentication from: {self.auth_file}")
        logger.info(f"Monitoring LinkedIn every {self.check_interval} seconds")
        logger.info("Press Ctrl+C to stop")
        logger.info("="*60)

        try:
            iteration = 0
            while True:
                iteration += 1
                logger.info(f"\n[Check #{iteration}] Checking LinkedIn...")

                results = self.check_linkedin()

                if results:
                    # Process messages
                    if self.config.get('monitor_messages', True):
                        messages = results.get('messages', [])
                        logger.info(f"Found {len(messages)} new message(s)")

                        for msg in messages:
                            msg_id = msg.get('id')
                            if msg_id and msg_id not in self.processed_items:
                                self.create_action_file('MESSAGE', msg)
                                self.processed_items.add(msg_id)

                    # Process notifications
                    if self.config.get('monitor_notifications', True):
                        notifications = results.get('notifications', [])
                        logger.info(f"Found {len(notifications)} new notification(s)")

                        for notif in notifications:
                            notif_id = notif.get('id')
                            if notif_id and notif_id not in self.processed_items:
                                self.create_action_file('NOTIFICATION', notif)
                                self.processed_items.add(notif_id)

                if once:
                    logger.info("Single check complete, exiting...")
                    break

                logger.info(f"Waiting {self.check_interval} seconds until next check...")
                time.sleep(self.check_interval)

        except KeyboardInterrupt:
            logger.info("\nLinkedIn Watcher stopped by user")
        except Exception as e:
            logger.error(f"Unexpected error: {e}", exc_info=True)

def main():
    parser = argparse.ArgumentParser(description='LinkedIn Watcher - Monitor LinkedIn')
    parser.add_argument('--once', action='store_true', help='Check once and exit')
    parser.add_argument('--vault-path', help='Path to Vault directory')
    parser.add_argument('--config', default='linkedin-config.json', help='Config file path')
    parser.add_argument('--auth-file', default='auth.json', help='Authentication file path')

    args = parser.parse_args()

    try:
        watcher = LinkedInWatcher(
            config_path=args.config,
            vault_path=args.vault_path,
            auth_file=args.auth_file
        )
        watcher.watch(once=args.once)
    except Exception as e:
        logger.error(f"Fatal error: {e}", exc_info=True)
        sys.exit(1)

if __name__ == '__main__':
    main()
